### ISSUE TITLE
Function parameter definitions throw an error when called

### ISSUE THREAD

**Issue by k88hudson** [mozilla/newtab-webextensions#9]
Here's an isolated example: 

https://github.com/k88hudson/webext-experiment-hello/commit/803f414044376469cc4e11a8652f4ad028ba679a

In this example, `hello.hello` takes a single parameter (a callback). When that callback is called, it does seem to be executed, however a couple of errors are thrown: 

<img width="736" alt="image" src="https://user-images.githubusercontent.com/1455535/29135422-14c76438-7d08-11e7-9eca-4fa0f2688e31.png">

**Comment by k88hudson** [comment]
@aswan do you see anything off in the test case I linked to? Or is this a limitation of the experiment api maybe?

**Comment by aswan** [comment]
There are a couple of problems with directly accepting a callback that way, the biggest one is that with out-of-process extensions, api.js runs in the parent process but extension code runs in a content process (typically the extension process).
If it meets your needs, writing this API as a webextension event would let you accept a callback and then invoke the callback when you like.  To implement an event, use the EventManager class:
http://searchfox.org/mozilla-central/rev/4b79f3b23aebb4080ea85e94351fd4046116a957/toolkit/components/extensions/ExtensionCommon.jsm#1413-1433

Our documentation is pretty sparse, I'm happy to help with any questions you have (but I'm in UTC+2 for the next few weeks), folks in #webextensions on IRC should also be able to help.

**Comment by k88hudson** [comment]
Ok thanks! That seems to work great 👍
